# Name: Project3_SlotMachine
# Purpose: This program simulates playing a slot machine.
#          It will print out 3 symbols to represent what symbols are on the slot machine.
#          DD = = Diamond, C = Cherry, B/BB/BBB = Bars, 7 = 7, 0 = 0
#          Based on what three symbols you get, you payout is then printed.
#
#Author: Timothy Bollig
#Date last edited: 10/22/2021
#Copyright: GNU General Public License v3.0
#Contact: bollig.timothy@gmail.com

################################################################################
################################################################################ 

#Function: get_symbols
#Purpose: Generates a three item character string of random symbols
#         representing the symbols on a slot machine.
#Output: Character vector of three symbols.
get_symbols <- function() {
  #Create character vector of all possible symbols.
  wheel <- c("DD", "7", "BBB", "BB", "B", "C", "0")
  #Randomly pick 3 of the symbols allowing repeats.  Adjust probability accordingly.
  sample(wheel, size = 3, replace = TRUE, 
         prob = c(0.03, 0.03, 0.06, 0.1, 0.25, 0.01, 0.52))
}

#Function: score
#Purpose: Determine payout amount based on symbols generated by get_symbols.
#Output: Integer representing payout of slot machine.
score <- function(symbols){
  #Identify cases for three of a kind and all bars.
  same <-  symbols[1] == symbols[2] && symbols[2] == symbols[3]
  bars <- symbols %in% c("B","BB","BBB")
  #Count number of diamonds and cherries in spin.
  diamonds <- sum(symbols == "DD")
  cherries <- sum(symbols == "C")
  
  #Determine prize
  if (same){
    #Checking if symbols are three of a kind
    #Create vector matching symbols to payout amounts.
    payouts <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, "B" = 10,
                 "C" = 10, "0" = 0)
    #Use unname to return only the symbol's value.
    #Use symbols[1] because if all symbols are same then you can simply look at first.
    prize <- unname(payouts[symbols[1]])
    
    #Check if two of the three symbols are diamonds.
  } else if (diamonds == 2){
    #Figure out what the other symbol is.
    #Create a logical vector based on position of diamonds.
    other_symbol <- symbols == "DD"
    #Return character at the position that is False for diamond.
    other_symbol <- symbols[!other_symbol]
    
    #Create vector matching symbols to payout amounts.
    payouts <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, "B" = 10,
                 "C" = 10, "0" = 0)
    #Payout as if three of a kind of other symbol.
    prize <- unname(payouts[other_symbol])
    
    #Check if one of the three symbols in a diamond.
  } else if (diamonds == 1){
    #Cases possible when you have 1 diamond. Starting with two of each other symbol.
    if (sum(symbols == "7") == 2){
      prize <- 80
    } else if (sum(symbols == "BBB") == 2){
      prize <- 40
    } else if (sum(symbols == "BB") == 2){
      prize <- 25
    } else if (sum(symbols == "B") == 2){
      prize <- 10
    } else if (cherries == 2){
      prize <- 10
    } else if (cherries == 1){
      prize <- 5
      #Check if other two symbols are B, BB, and/or BBB to create any combo of bars.
    } else if (sum(symbols %in% c("B","BB","BBB")) == 2){
      prize <- 5
    } else{
      prize <- 0
    }
    #Any combination of all bars gets a payout of 5.
  } else if (all(bars)){
    prize <- 5
    #cherries+1 is used because indexing starts at 1.
  } else{
    prize <- c(0,2,5)[cherries + 1]
  }
  
  #Prize doubles for each diamond.
  prize * 2 ^ diamonds
}

#Function: play
#Purpose: Simulate pulling a lever on a slot machine.
#Output: Three characters representing symbols on the slot machine.
#        Integer representing payout of slot machine.
play <- function(){
  #Pull lever and get three symbols.
  symbols <- get_symbols()
  #Print out those symbols.
  print(symbols)
  #Print payout based on symbols.
  score(symbols)
}
##################################End of File#################################